### PR TITLE
 Interactive visualizations for aslib scenarios

### PR DESCRIPTION
**Pull request by damirpolat**
Added Kathy Chawla's scripts for interactive visualizations of aslib scenarios. The script needs location of arff files for algorithm runs and will then generate respective interactive html files.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, looks good! Could you also please add a short readme file that explains how to use this?

**Comment by damirpolat** [comment]
> Thanks, looks good! Could you also please add a short readme file that explains how to use this?

Done, thanks!

**Comment by larskotthoff** [comment]
Great, thanks. Looks like some .pyc files sneaked into your last commit -- could you remove those please?

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
